version: '3'
services:
  db:
    image: redis
    ports:
     - "6379:6379"
  backend:
    image: rasje17/fortune-backend:latest
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      - REDIS_DNS=db
    depends_on:
      - db
  frontend:
    image: rasje17/fortune-frontend:latest
    ports:
      - "8080:8080"
    links:
      - backend
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    command: "/frontend"
    
