apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: REDIS_DNS
              value: db
          image: rasje17/fortune-backend:latest
          name: backend
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
