apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: redis
          name: db
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
