apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_DNS
              value: backend
            - name: BACKEND_PORT
              value: "9000"
          image: rasje17/fortune-frontend:latest
          name: frontend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
