name: Fortune Cookie
on:
  push:
    branches:
      - "develop"
env:
  docker_username: ${{ secrets.DOCKER_USER }}
  docker_password: ${{ secrets.DOCKER_PW }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    name: Clone down repo
    runs-on: [self-hosted, label-1]
    steps:
    - uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: |
          .
          !.git
  Docker-image:
    runs-on: [self-hosted, label-1]
    needs: Clone-down
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: build backend
        run: chmod +x ci/build-docker-backend.sh && ci/build-docker-backend.sh
      - name: build frontend
        run: chmod +x ci/build-docker-frontend.sh && ci/build-docker-frontend.sh 
  Test:
    runs-on: [self-hosted, label-1]
    needs: Docker-image
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Execute component test
        run: chmod +x ci/component-test.sh && ci/component-test.sh
